# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
FROM python:alpine

ENV JJBVERSION 1.6.2

RUN apk add --no-cache bash
RUN pip install jenkins-job-builder==${JJBVERSION}

VOLUME /jjb-jobs
VOLUME  /output

WORKDIR /jjb-jobs

ENTRYPOINT ["jenkins-jobs", "test", "-o", "/output"]